### ISSUE TITLE
NO always returns to program counter 0

### ISSUE THREAD

**Issue by Slord6** [SoicBRcode/IsThatAMotherFrickingSpecificAnimeReferenceLang#1]
Hi there!

I haven't pulled the code to check, but I'm sure that a `NO` instruction can only ever set the program counter to zero as there's no check on accumulator being `0`, and `LastZeroInstruction` is only assigned to on initalisation.

**Comment by SoicBRcode** [comment]
Oh no! I totally forgot about doing that check! I will fix this problem as soon as i can get to my PC. Thanks for reporting :)

**Comment by SoicBRcode** [comment]
Fixed!
